# sitemap_config.yml

site_url: "https://drwang.ca"

static_pages:
  - path: "/"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/treatments.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/acupuncture.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/medicine.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/patient.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/case-reports.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/fees.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/testimonial.html"
    lastmod: "2025-07-30"
    changefreq: "yearly"
  - path: "/publications.html"
    lastmod: "2025-07-30"
    changefreq: "yearly"
  - path: "/about.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"
  - path: "/contact.html"
    lastmod: "2025-07-30"
    changefreq: "monthly"

case_reports_folder: "./casereports"
case_reports_changefreq: "weekly"
lastmod_today: true
