name: Remove Refresh Meta

on:
  workflow_dispatch:
  push:
    paths:
      - 'casereports/acupuncture-for*.html'

jobs:
  remove_refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Run Python script
        run: python remove_refresh.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Removed meta refresh tags" || echo "No changes to commit"
          git push
